server:
    port: 8080
#需要修改行： 9 、8、 11  、39 、40 、41 、     如果是直接用 就不用改这俩 70 、71
spring:
    datasource:
        druid:
            one:  #数据源1
                driver-class-name: com.mysql.jdbc.Driver
                url: jdbc:mysql://x.x.x.x:3306/db1 # 自己修改
                username: root
                password: x
                #初始化时建立物理连接的个数
                initialSize: 1
                #池中最大连接数
                maxActive: 20
                #最小空闲连接
                minIdle: 1
                #获取连接时最大等待时间，单位毫秒
                maxWait: 60000
                #有两个含义：
                #1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
                #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
                timeBetweenEvictionRunsMillis: 60000
                #连接保持空闲而不被驱逐的最小时间，单位是毫秒
                minEvictableIdleTimeMillis: 300000
                #使用该SQL语句检查链接是否可用。如果validationQuery=null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
                validationQuery: SELECT 1 FROM DUAL
                #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
                testWhileIdle: true
                #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
                testOnBorrow: false
                #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
                testOnReturn: false
                # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
                filters: stat,wall,slf4j

            two: #数据源2
                driver-class-name: com.mysql.jdbc.Driver
                url: jdbc:mysql://x.x.x.x:3306/db2
                username: root
                password: x
                #初始化时建立物理连接的个数
                initialSize: 1
                #池中最大连接数
                maxActive: 20
                #最小空闲连接
                minIdle: 1
                #获取连接时最大等待时间，单位毫秒
                maxWait: 60000
                #有两个含义：
                #1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
                #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
                timeBetweenEvictionRunsMillis: 60000
                #连接保持空闲而不被驱逐的最小时间，单位是毫秒
                minEvictableIdleTimeMillis: 300000
                #使用该SQL语句检查链接是否可用。如果validationQuery=null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
                validationQuery: SELECT 1 FROM DUAL
                #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
                testWhileIdle: true
                #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
                testOnBorrow: false
                #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
                testOnReturn: false
                # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
                filters: stat,wall,slf4j
               

## 该配置节点为独立的节点，不是在在spring的节点下
mybatis:
    mapper-locations: classpath:mapper/*/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.example.springboot2pc.entity  # 注意：对应实体类的路径
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印sql